# roles/sepolicy/tasks/main.yml
# Install an SELinux policy on the server
---

- name: Check whether policy is already installed
  stat:
    path: /etc/selinux/targeted/modules/active/modules/syncedwww.pp
  register: policy

- name: Put the policy definition on the server
  copy:
    src: syncedwww.te
    dest: /tmp/syncedwww.te

- name: Make sure policy utils are installed
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - checkpolicy
    - policycoreutils-python

- name: Compile module (step 1)
  command: checkmodule -M -m -o /tmp/syncedwww.mod /tmp/syncedwww.te

- name: Compile module (step 2)
  command: semodule_package -o /tmp/syncedwww.pp -m /tmp/syncedwww.mod

- name: Install compiled policy
  command: semodule -i /tmp/syncedwww.pp

- name: Remove artefacts
  file:
    path: /tmp/syncedwww.{{ item }}
    state: absent
  with_items:
    - mod
    - pp
